### ISSUE TITLE
drmemory failed to locate config directory in Android

### ISSUE THREAD

**Issue by colordancer** [DynamoRIO/drmemory#1857]
drmemory 1.9.1-RC1 supports native Android applications. But Android's wrap mechanism could help drmemory extend supports for Android Apps. 

Now I could successfully use drmemory to invoke an App. But during the start process, I was stuck at the config error.

> I/androidWrapper.sh( 9828): INFO: targeting application: "/system/bin/app_process32"
I/androidWrapper.sh( 9828): INFO: app cmdline: "/system/bin/app_process" "/system/bin" "--application" "--nice-name=com.ryu.asandemo" "com.android.internal.os.WrapperInit" "14" "21" "android.app.ActivityThread" 
I/androidWrapper.sh( 9828): INFO: logdir is "/data/local/tmp/drlog"
I/androidWrapper.sh( 9828): INFO: symcache_dir is "/data/local/tmp/drlog/symcache"
I/androidWrapper.sh( 9828): INFO: DynamoRIO configuration directory is /system/xbin/DrMemory/temp//.dynamorio
I/androidWrapper.sh( 9828): INFO: configuring app_process32 pid=9830 dr_ops="-disable_traces -bb_single_restore_prefix -max_bb_instrs 256 -vm_size 256M -no_enable_reset -logdir `/data/local/tmp/drlog/dynamorio` "
I/androidWrapper.sh( 9828): ERROR: failed to register DynamoRIO configuration for "app_process32"(9830) dr_ops="-disable_traces -bb_single_restore_prefix -max_bb_instrs 256 -vm_size 256M -no_enable_reset -logdir `/data/local/tmp/drlog/dynamorio` ".
I/androidWrapper.sh( 9828): Error code 13 (failed to locate a valid config directory)

The config directory is `/system/xbin/DrMemory/temp/.dynamorio`. Its permission was set already.
> 1|root@hammerhead:/system/xbin/DrMemory # ls -al                        
-rwxrwxrwx root     root         3932 2016-02-23 11:42 README
drwxrwxrwx root     root              2016-02-26 13:55 bin
drwxrwxrwx root     root              2016-02-23 11:42 docs
drwxrwxrwx root     root              2016-02-23 11:42 drmemory
drwxrwxrwx root     root              2016-02-23 11:42 drmf
drwxrwxrwx root     root              2016-02-23 11:42 dynamorio
-rwxrwxrwx root     root        27021 2016-02-23 11:42 license.txt
drwxrwxrwx root     root              2016-02-26 13:56 temp
drwxrwxrwx root     root              2016-02-23 11:42 tools

So why did I get the error: `Error code 13 (failed to locate a valid config directory)`?

What's interesting is, if I directly use drmemory to run app_process, without other parameters, I won't get those errors:
> root@hammerhead:/system/xbin/DrMemory/bin # ./drmemory -- /system/bin/app_process32
~~Dr.M~~ Dr. Memory version 1.9.1
~~Dr.M~~ (Uninitialized read checking is not yet supported for ARM)
~~Dr.M~~ WARNING: application is missing line number information.
~~Dr.M~~ 

This does not make sense.

**Comment by derekbruening** [comment]
Xref https://groups.google.com/forum/#!topic/drmemory-users/FtngBH43Rnk

Please clarify:

+ What is the precise command line and the wrap command line for the app_process32 execution?
+ Are you running in an interactive adb shell or in a batch command to adb shell?  This makes a difference in things like the current working directory, which is a fallback check for the config dir.
+ How are you specifying the config dir?  Please specify which relevant env vars you are setting.
+ What is the effective user id the app is being run as, or if you prefer what is the writability for that user?  Our checks look for target directories being writable either by geteuid() if it matches the directory's owner or by other.
+ Does plain DynamoRIO run?  I.e., try `drmem-path/dynamorio/bin32/drrun -v -debug -- ls`

We have been unable to reproduce these errors.  Perhaps you could run either bin32/drrun or bin/launcher in gdb and try to see what's going on?  Step into open_config_file() called from dr_register_process().

**Comment by colordancer** [comment]
- What is the precise command line and the wrap command line for the app_process32 execution?

A: Wrap command line is `"/system/bin/app_process" "/system/bin" "--application" "--nice-name=com.ryu.asandemo" "com.android.internal.os.WrapperInit" "14" "21" "android.app.ActivityThread" `

- Are you running in an interactive adb shell or in a batch command to adb shell? This makes a difference in things like the current working directory, which is a fallback check for the config dir.

A: I was running in an interactive adb shell during setting up the environment. But please be aware that if I run the App in wrap way, the App's process is not manually started by me in Adb shell. In stead, it is started(forked) by system_server process. This logic is so sophisticated to describe in language. If you think the problem probably lies here, I could explain to you in details.  

- How are you specifying the config dir? Please specify which relevant env vars you are setting.

A: I specify config dir in the wrap shell script:

> #!/system/bin/sh
export DYNAMORIO_CONFIGDIR=/system/xbin/DrMemory/temp/
exec /system/xbin/DrMemory/bin/drmemory -show_reachable -v -logdir /data/local/tmp/drlog -- $*

- What is the effective user id the app is being run as, or if you prefer what is the writability for that user? Our checks look for target directories being writable either by geteuid() if it matches the directory's owner or by other.

A: The App's user id is `u0_a55`:
> drwxr-x--x u0_a55   u0_a55            1970-04-25 11:20 com.ryu.asandemo

The config directory's permissions:
> drwxrwxrwx root     root              2016-02-26 13:56 temp

- Does plain DynamoRIO run? I.e., try drmem-path/dynamorio/bin32/drrun -v -debug -- ls

A: I believe so. Because just as I said previously, I'm able to use drmemory to start the single app_process. But I failed to use drmemory to start an App, which is basically also a app_process but started in a more sophisticated process.

**Comment by derekbruening** [comment]
Unfortunately we did not get a chance to try and repro for the recent release.  It is not clear what the issue is: it will take some debugging.  Contributions welcome.

**Comment by zhaoqin** [comment]
There are two issues I have seen so far on my device: Nexus 6, Android N developer preview

When running shell as root, the $HOME directory is /
/ is mounted as read-only, however, the file permission shows writable.
```
> ./adb shell
shamu:/ # ls -ld /
drwxr-xr-x 19 root root 0 1970-05-21 14:03 /
shamu:/ # mkdir abc
mkdir: 'abc': Read-only file system
```
This confused Dr. Memory. Dr. Memory thinks that it could create a config directory, but failed.
So when we run the Dr. Memory directly as root, it may fail to inject the process, which is really caused by this failed to create config directory. This can be worked around by setting DYNAMORIO_CONFIGDIR=/data/local/tmp

When we use /data/local/tmp as config dir, and try to run the Android pkg with a wrapper,
We saw that we checked /data/local/tmp/dynamorio is writable, but failed to create the config file
```
03-25 14:38:06.817  9397  9397 I aw.sh   : dir: /data/local/tmp/dynamorio, st_mode: 0x41ff
03-25 14:38:06.818  9397  9397 I aw.sh   : 0 drfront_access: fname: /data/local/tmp/dynamorio
03-25 14:38:06.818  9397  9397 I aw.sh   : 1 drfront_access: fname: /data/local/tmp/dynamorio
03-25 14:38:06.818  9397  9397 I aw.sh   : 2 drfront_access: fname: /data/local/tmp/dynamorio, ret false
03-25 14:38:06.819  9397  9397 I aw.sh   : 2 drfront_access: fname: /data/local/tmp/dynamorio, euid 10050, st.st_uid: 0, st_mode: 41ff, mode 2
03-25 14:38:06.819  9397  9397 I aw.sh   : 3 drfront_access: fname: /data/local/tmp/dynamorio, ret true
03-25 14:38:06.819  9397  9397 I aw.sh   : w access: 1
03-25 14:38:06.819  9397  9397 I aw.sh   : fname /data/local/tmp/dynamorio/app_process32.9399.1config32
03-25 14:38:06.819  9397  9397 I aw.sh   : fname: /data/local/tmp/dynamorio/app_process32.9399.1config32, mode: wb, f 0, 13
03-25 14:38:06.820  9397  9397 I aw.sh   : Error: Permission denied
03-25 14:38:06.820  9397  9397 I aw.sh   : f=0, process_name app_process32, pid 9399, global no, dr_platform 0
03-25 14:38:06.820  9397  9397 I aw.sh   : ERROR: failed to register DynamoRIO configuration for "app_process32"(9399) dr_ops="-disable_traces -bb_single_restore_prefix -max_bb_instrs 256 -vm_size 256M -no_enable_reset -logdir `/data/local/tmp/drmemorylog/dynamorio` ".
03-25 14:38:06.820  9397  9397 I aw.sh   : Error code 13 (failed to locate a valid config directory)
```
```
130|shamu:/ # ls -ld /data/local/tmp/dynamorio
drwxrwxrwx 2 root root 4096 2016-03-24 18:39 /data/local/tmp/dynamorio
```
For some reason, we failed to create new config file in the writable directory and the error msg is "Permission Denied", and that causes Dr. Memory fail to inject the process.

**Comment by zhaoqin** [comment]
Update, the failed to create directory is caused by selinux policy.
Quick workaround is to disable the policy: `setenforce 0`

**Comment by derekbruening** [comment]
Taking over to implement the fixes.

The plan is in multiple parts:

1) Handle $HOME being writable but mounted read-only: I am adding a new routine  drfront_dir_try_writable() which tries to create a file.  We call it from  drfront_access(,DRFRONT_WRITE,) on a directory after the permission bit check succeeds.  (I added it to drfront_access partly to avoid compat challenges of changing DrM to rely on a bugfix release.)  

2) Also add an euid==0 check where we assume that root has read and write access to every file and has execute access to any file with at least one execute bit set (not always true on recent Linux but good enough here).

3) We make the .dynamorio subdir that we create be world-writable, but only for Android.  On other OS's we expect $HOME to actually work and are ok with a subdir that is only writable by the current user.

4) SELinux: as it is difficult to preserve the extended file attributes on tar or adb push, we'd need to do a chcon in drconfiglib.  However, I cannot manage to find any context that works that I can set.

The only place I've found that I can write as the app is /sdcard, and I cannot set its context:

```
# ls -ldZ /sdcard
lrwxrwxrwx root     root              u:object_r:rootfs:s0 sdcard -> /storage/self/primary
# ls -Z /storage/self/primary
lrwxrwxrwx root     root              u:object_r:storage_file:s0 primary -> /mnt/user/0/primary
# ls -Zd /mnt/user/0/primary
lrwxrwxrwx root     root              u:object_r:mnt_user_file:s0 primary -> /storage/emulated/0
# ls -Zd /storage/emulated/0
drwxrwx--x root     sdcard_rw          u:object_r:fuse:s0 0
```

These fail:
```
# chcon u:object_r:rootfs:s0 /data/local/tmp/.dynamorio
chcon: '/data/local/tmp/.dynamorio' to u:object_r:rootfs:s0: Permission denied
# chcon u:object_r:fuse:s0 ../.dynamorio
chcon: '../.dynamorio' to u:object_r:fuse:s0: Permission denied
```

This is insufficient:
```
# chcon u:object_r:system_data_file:s0 ../.dynamorio
03-27 16:34:12.095 18684 18684 W drrun   : type=1400 audit(0.0:76): avc: denied { write } for name=".dynamorio" dev="mmcblk0p30" ino=261267 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=0
```

This too:
```
# chcon u:object_r:apk_private_data_file:s0 ../.dynamorio
03-27 16:34:59.431 18759 18759 W drrun   : type=1400 audit(0.0:77): avc: denied { getattr } for path="/data/local/tmp/.dynamorio" dev="mmcblk0p30" ino=261267 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_private_data_file:s0 tclass=dir permissive=0
```

And this:
```
# chcon u:object_r:storage_file:s0 ../.dynamorio
03-27 16:39:44.139 18990 18990 W drrun   : type=1400 audit(0.0:82): avc: denied { write } for name=".dynamorio" dev="mmcblk0p30" ino=261267 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:storage_file:s0 tclass=dir permissive=0
```

And this:
```
# chcon u:object_r:mnt_user_file:s0 ../.dynamorio
03-27 16:43:09.650 19231 19231 W drrun   : type=1400 audit(0.0:85): avc: denied { write } for name=".dynamorio" dev="mmcblk0p30" ino=261267 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:mnt_user_file:s0 tclass=dir permissive=0
```

So I'll add a fallback of /sdcard, and I'll document that as a last resort the user should turn off SELinux (via `setenforce 0`).

5) Yet another problem is that the permission bit check fails for /sdcard as the app, b/c it is o-w:

```
/data/local/tmp/build_android_dbg # ls -ld /storage/emulated/0
drwxrwx--x root     sdcard_rw          2016-03-27 16:29 0
```

This user is not in the sdcard_rw group as "id" in wrap.sh shows:

```
03-27 19:08:04.732 22679 22679 I wrap.sh : uid=10034(u0_a34) gid=10034(u0_a34) groups=10034(u0_a34),3001(net_bt_admin),3002(net_bt),3003(inet),9997(everybody),50034(all_a34) context=u:r:untrusted_app:s0:c512,c768
```

No, Android does not have non-UNIX behavior elsewhere: this user fails to write to /data/local/tmp which is also o-w.  There is something weird about this particular dir.  We either have to skip the bits check, or hardcode this dir.

**Comment by derekbruening** [comment]
/sdcard isn't working for the calculator app as it fails to create /sdcard/.dynamorio:
```
03-27 21:18:20.506  3778  3778 I wrap.sh : ERROR: process app_process32 registration failed: check config dir /sdcard/ permissions
```

Trying to create w/o checking the bits: still fails.

Going back and running chrome -- confirmed, it can create it:

```
# ls -ld /sdcard/.dynamorio
drwxrwx--x root     sdcard_rw          2016-03-27 20:49 .dynamorio
```

Chrome maybe has different privs?  But wrap.sh was able to mkdir!
I guess the Zygote at that point is already different, b/c calc can't:
```
03-27 21:42:52.932  4343  4343 I wrap.sh : mkdir: '/sdcard/mydir': Permission denied
```

Seems like we need:
```
# chmod o+rw /sdcard
```
Note that doing that to /data/local/tmp is not sufficient as we still have selinux failures there.

Hmm, it doesn't work:

```
/data/local/tmp/build_android_dbg # chmod o+rw /sdcard
/data/local/tmp/build_android_dbg # ls -ld /storage/emulated/0
drwxrwx--x root     sdcard_rw          2016-03-27 21:07 0
/data/local/tmp/build_android_dbg # chmod o+rw /storage/emulated/0
/data/local/tmp/build_android_dbg # ls -ld /storage/emulated/0
drwxrwx--x root     sdcard_rw          2016-03-27 21:07 0
/data/local/tmp/build_android_dbg # chmod a+w /storage/emulated/0
/data/local/tmp/build_android_dbg # ls -ld /storage/emulated/0
drwxrwx--x root     sdcard_rw          2016-03-27 21:07 0
/data/local/tmp/build_android_dbg # chmod 777 /storage/emulated/0
/data/local/tmp/build_android_dbg # ls -ld /storage/emulated/0
drwxrwx--x root     sdcard_rw          2016-03-27 21:07 0
```

Same results under "setenforce 0".

I can't make a subdir or file world-writable either:

```
/data/local/tmp/build_android_dbg # mkdir /sdcard/logs
/data/local/tmp/build_android_dbg # ls -ld /sdcard/logs
drwxrwx--x root     sdcard_rw          2016-03-27 21:27 logs
/data/local/tmp/build_android_dbg # chmod 777 /sdcard/logs
/data/local/tmp/build_android_dbg # ls -ld /sdcard/logs
drwxrwx--x root     sdcard_rw          2016-03-27 21:27 logs
/data/local/tmp/build_android_dbg # touch /sdcard/logs/foo
/data/local/tmp/build_android_dbg # ls -l /sdcard/logs
-rw-rw---- root     sdcard_rw        0 2016-03-27 21:27 foo
/data/local/tmp/build_android_dbg # chmod 777 /sdcard/logs/foo
/data/local/tmp/build_android_dbg # ls -l /sdcard/logs
-rw-rw---- root     sdcard_rw        0 2016-03-27 21:27 foo
```

So how do the Valgrind instructions that use /sdcard work?  Looking around more, instructions that use the app's data dir are more common than ones using /sdcard.

And indeed this works:
```
# export DYNAMORIO_CONFIGDIR=/data/data/com.android.calculator2
```
And this (so our perm checks like it):
```
# export TMPDIR=/data/data/com.android.calculator2
```

How can we find that automatically?  Parse the args?  Running "set" in the wrapper script shows no env vars for us.  We could iterate over /data/data and look for our userid?  I guess the user has to set it.

**Comment by colordancer** [comment]
@zhaoqin Have you succeeded to run an App with DrMemory wrapper in Nexus 6?

**Comment by derekbruening** [comment]
There are problems even in plain DR: https://github.com/DynamoRIO/dynamorio/issues/1912

**Comment by colordancer** [comment]
@derekbruening If this problem comes from SELinux, I think it's acceptable. But I haven't tried it through. Will get you back soon.

**Comment by derekbruening** [comment]
To clarify: as you can see in the details I wrote above and in recent commits, the config dir issue is solved, but only with help from the user to set TMPDIR to point at the target app's directory in /data/data (or alternatively to disable SELinux).

These commits fixed the config dir issue for DynamoRIO.  This issue is not yet closed b/c these need to be propagated to Dr. Memory.

e2763d6 DrMi#1857 Android config, part 1: try creating a file in drfront_access(,DRFRONT_WRITE,)
dc7b268 DrMi#1857 Android config, part 2: add root user support in drfront_access()
d7407f3 DrMi#1857 Android config, part 3: make config dir world-writable on Android
a353e44 DrMi#1857 Android config, part 4: better error messages
b238a0d DrMi#1857 Android config, part 5: documentation

DynamoRIO/dynamorio#1912 is a problem running Java apps independent of config dirs and independent of SELinux.  It is an application crash that needs debugging.

**Comment by colordancer** [comment]
After disable SeLinux, I haven't got config error. But I still failed to start the App, due to EOFException:
`05-25 13:08:30.019 W/Zygote  (  219): Error reading pid from wrapped process, child may have died
05-25 13:08:30.019 W/Zygote  (  219): java.io.EOFException
05-25 13:08:30.019 W/Zygote  (  219): 	at libcore.io.Streams.readFully(Streams.java:83)
05-25 13:08:30.019 W/Zygote  (  219): 	at java.io.DataInputStream.readInt(DataInputStream.java:103)
05-25 13:08:30.019 W/Zygote  (  219): 	at com.android.internal.os.ZygoteConnection.handleParentProc(ZygoteConnection.java:979)
05-25 13:08:30.019 W/Zygote  (  219): 	at com.android.internal.os.ZygoteConnection.runOnce(ZygoteConnection.java:276)
05-25 13:08:30.019 W/Zygote  (  219): 	at com.android.internal.os.ZygoteInit.runSelectLoop(ZygoteInit.java:788)
05-25 13:08:30.019 W/Zygote  (  219): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)`

**Comment by derekbruening** [comment]
It always says "EOFException", *after* the real error.  Almost certainly you are hitting the known problems in DynamoRIO/dynamorio#1912

**Comment by derekbruening** [comment]
This issue covers just the config dir issues, with a fix forthcoming.  Issues running beyond DynamoRIO/dynamorio#1912 are under #1881.
